### ISSUE TITLE
Using VCF files?

### ISSUE THREAD

**Issue by joneill-code** [harmslab/gpmap#15]
I have DST information for drug resistant and susceptible bacteria. How can I convert them to a genotype-phenotype map for your gpmap & epistasis modules?

**Comment by Zsailer** [comment]
GPMap's read/write module is entirely based on [Pandas](https://pandas.pydata.org/). 

The easiest way to get VCF into GPMap is to write code that reads the data into a Pandas dataframe. Maybe checkout the [`read_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_table.html#pandas.read_table) function in Pandas. Then, format that dataframe to have the following columns: `["genotypes", "phenotypes", "stdeviations", "n_replicates"]`. Finally, pass that dataframe into GPMap using the `read_dataframe` method.

Here is some pseudocode to guide you:

```python
import pandas as pd

from gpmap import GenotypePhenotypeMap

# ------ Code to read data in Dataframe  ----
vcf_filename = "/path/to/file"
df = pd.read_table(vcf_filename, ...)

# Reformat df to have columns mentioned above:
...

# ------ Pass data to gpmap  ----
# Define a wildtype or reference sequence
wildtype_seq = "..."

# Read data into map object
gpm = GenotypePhenotypeMap.read_dataframe(df, wildtype=wildtype)
```

If you get that working, let us know and we maybe can add your code to `gpmap` for other users?

**Comment by joneill-code** [comment]
Thanks! I'll be working on this, and gladly offer my code. Below is a sample VCF format. What would a sample genotype look like from an entry below? Phenotype is simple enough in this case- 1 or 0. (R or S). I'm assuming stdeviations would be 0 in our case? And n_replicates?
Thanks, again


![screenshot from 2018-08-13 14 30 27](https://user-images.githubusercontent.com/35746680/44059249-9c4dd4b2-9f05-11e8-8093-e2dd0a1eac47.png)

**Comment by joneill-code** [comment]
Keep me posted on your thoughts.

**Comment by Zsailer** [comment]
Ok--I am not familiar with VCF format, and it's not obvious to me after a quick glance at the example above. I'll try to find time in the next day or two, and let you know.

**Comment by joneill-code** [comment]
Thank you. Let me know if I can be of service. Each entry beginning with the chromosome (Just 1 in this case for a bacterium.) It is then followed by the position in the genome, the "REFerence" & "ALTernative" SNP. INFO and FORMAT will tell you which gene & the type of variant.

**Comment by Zsailer** [comment]
GPMap requires a reference (or `wildtype`) genotype and a list of genotypes. 

In this case, I think your reference genotype is the "REF" column (joined together). The "ALT" column encodes the mutant genotypes. Each alternate site, then, is represented as the wildtype genotype with the ALT residues substituted. In your example above, that looks like:
```
wildtype = "CATGGGGC"

genotypes = [
    "CATGGGGC",
    "AATGGGGC",     # ALT = A
    "CGTGGGGC",     # ALT = G
    "CACGGGGC",     # ALT = C
    "CATCGGGC",     # ALT = C
    "CATGAGGC",     # ALT = A
    "CATGGCGC",     # ALT = C
    "CATGGGAC",     # ALT = A
    "CATGGGGG",     # ALT = G
]
```

This looks ignores the position of these substitutions (POS column), but you can keep track of that information in the dataframe you build. 

Does this make sense?

**Comment by Zsailer** [comment]
I should also mention--if you have a large number of genotypes in your file, there are utility functions in `gpmap` that can help you enumerate genotypes quickly. 

One thing you can do is construct a `mutations` dictionary programmatically. This dictionary maps mutations to their site number in the genotypes. In your file above, this would look like:
```python

wildtype = "CATGGGGC"

mutations = {
    0: ["C", "A"],
    1: ["A", "G"],
    2: ["T", "C"],
    3: ["G", "C"],
    4: ["G", "A"],
    5: ["G", "C"],
    6: ["G", "A"],
    7: ["C", "G"]
}
```
You'll notice, I just took the "REF" and "ALT" columns and combined them to make a list of residues at each site. 

Then, you can use `gpmap.utils.mutations_to_genotypes` function to generate genotypes. 
```python 
import gpmap

genotypes = gpmap.utils.mutations_to_genotypes(wildtype, mutations)
```
