### ISSUE TITLE
what to do about extra data? 

### ISSUE THREAD

**Issue by Zsailer** [harmslab/gpmap#16]
Need to properly handle extra data that isn't used by GPMap. Right now, GPMap ignores extra data annotated on each genotype. Users however, will likely want to keep this information together. 

The question is, should we expose these attributes through the GPMap interface. Or should they only live in the underlying GPMap DataFrame?

**Comment by harmsm** [comment]
I think the attributes should be exposed.  (Maybe these could be exposed under something like `gpmap.meta.attr1`, `gpmap.meta.attr2`, etc.)

There is also the special instance of the extra data being a different phenotype.  I would like to use GPMap for maps in which each genotype has a phenotype that depends on an external condition.  There seem to be two possible ways forward: either have multiple gpmap instances or alter gpmap so it holds multiple phenotypes.  The latter makes the most sense to me.  For genotypes with a single phenotype, gpmap could expose a float for each genotype; if multiple phenotype columns are specified, the phenotype for each genotype would be a vector.  

I would be happy to implement if this seems like a reasonable tack.

**Comment by Zsailer** [comment]
That's an important point. Multiple phenotypes should be added. Funny enough, I implemented a the notion of *multiple phenotypes* in a separate project called [latticegpm](https://github.com/harmslab/latticegpm). Not sure if this is the best way to implement.

Here, the user sets the `phenotype_type` attribute (see this [line](https://github.com/harmslab/latticegpm/blob/9b5b017689caf21188589b44b827c4596e18a63c/latticegpm/gpm.py#L104)) that matches some column name in the underlying DataFrame. GenotypePhenotypeMap then switches its phenotype array to that column in the dataframe. That way, the `phenotypes` attribute always returns a 1:1 mapping of genotype to phenotype. But they phenotype can be changed by setting this attribute.

**Comment by harmsm** [comment]
+ I like the fact that `phenotypes` always returns a 1D vector, mapped 1:1 to genotype, in this implementation.  

+ It does, however, seem like it could lead to difficult-to-detect bugs, particularly in a jupyter notebook context where cells may be run in any order.  A call like `gpm.phenotype_type("type1")` invisibly (to the user) changes the behavior of a different attribute (`gpm.phenotypes`).  We could argue that we should just trust the user, but it makes me a bit nervous.  

+ `phenotypes[0,:]` is certainly uglier, but explicitly indicates you want the first phenotype.  Further, a very natural data structure for a phenotype vs. environment would be a list of environmental conditions, which would then naturally map back to the `phenotypes` array.  

Comparing the implementations, however, makes me favor the `phenotype_type` approach.  (Maybe change the method name to `set_phenotype_type`, so it's clear that this is not just a getter). 

```
# Array style
env_temperatures = [0,25,37]
for i, T in enumerate(env_temperatures):
    print(gpm.phenotypes[i,:]) # phenotype at that temperature
```

```
# Phenotype type setter
env_temperatures = [0,25,37]
for T in env_temperatures:
    gpm.phenotype_type(T)
    print(gpm.phenotypes) # phenotype at that temperature
```
