### ISSUE TITLE
GenotypePhenotypeMap throws error

### ISSUE THREAD

**Issue by jamaltas** [harmslab/gpmap#6]
Error:

**AttributeError: GenotypePhenotypeMap instance has no attribute '_indices'** 

When using code from tutorial:

from gpmap import GenotypePhenotypeMap

# Create list of genotypes and phenotypes
wildtype = "AA"
genotypes = ["AA", "AV", "AM", "VA", "VV", "VM"]
phenotypes = [1.0, 1.1, 1.4, 1.5, 2.0, 3.0]

# Create GenotypePhenotypeMap object
gpm = GenotypePhenotypeMap(wildtype, genotypes, phenotypes)

Attempted on two machines with same result.

**Comment by Zsailer** [comment]
How did you install `gpmap`? Did you clone it and install? Or install using `pip`?

**Comment by jamaltas** [comment]
Pip. I just got home so I can try it on my home computer tonight. Perhaps
the clunky university software is interfering with the installation.

**Comment by Zsailer** [comment]
Ok, let us know! Thanks!

**Comment by jamaltas** [comment]
It works perfectly fine on Linux using git clone. Not sure if the trouble
was with windows or not. Thanks!

**Comment by Zsailer** [comment]
Great! Let us know if you come across anymore problems. Closing this!
